#!/usr/bin/env bash

set -euo pipefail

git_root=$(git rev-parse --show-toplevel)

fourmolu=$(nix-build "${git_root}/nix/pkgs.nix" --attr haskellPackages.fourmolu  --no-out-link)

standard_options=(\
  --ghc-opt -XBangPatterns \
  --ghc-opt -XPatternSynonyms \
  --ghc-opt -XTypeApplications \
  --ghc-opt -XTypeOperators \
)

exec "${fourmolu}/bin/fourmolu" "${standard_options[@]}" "$@"
