#!/usr/bin/env bash

set -euo pipefail

git_root=$(git rev-parse --show-toplevel)

nixpkgs_fmt=$(nix-build "${git_root}/nix/pkgs.nix" --attr nixpkgs-fmt  --no-out-link)

exec "${nixpkgs_fmt}/bin/nixpkgs-fmt" "$@"
