name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v16
        name: Install Nix
        with:
          install_url: https://releases.nixos.org/nix/nix-2.6.0/install
          nix_path: nixpkgs=./nix/pkgs.nix
      - uses: cachix/cachix-action@v8
        name: Set up Cachix
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-build
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Checkout
      - uses: cachix/install-nix-action@v16
        name: Install Nix
        with:
          install_url: https://releases.nixos.org/nix/nix-2.6.0/install
          nix_path: nixpkgs=./nix/pkgs.nix
      - uses: cachix/cachix-action@v8
        name: Set up Cachix
        with:
          name: awakesecurity
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          ./scripts/fourmolu --mode check **/*.hs
          ./scripts/nixpkgs-fmt --check **/*.nix
